meta_product_name: "Anouche création"
meta_title: "Anouche création, bjoux fantaisie"
meta_description: "Anouche création, bijoux fantaisie réalisés par mes soins dans mon petit atelier à côté de Grenoble"
meta_image: "anouche-creation.gif" # should exist in `app/assets/images/`
